#!/usr/bin/env bash

# Exit immediately if a command exits with a non-zero status, 
# treat unset variables as errors, and fail if any command in a pipeline fails
set -euo pipefail

script_dir="$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)"
cd $script_dir
dry="0"

while [[ $# > 0 ]]; do
    if [[ "$1" == "--dry" ]]; then
        dry="1"
    fi
    shift
done

log() {
    if [[ $dry == "1" ]]; then
        echo "[DRY_RUN]: $@"
    else
        echo "$@"
    fi
}

execute() {
    log "execute: $@"
    if [[ $dry == "1" ]]; then
        return
    fi

    "$@"
}

log "-------- dev-env --------"

copy_dir() {
    from=$1
    to=$2

    pushd $from > /dev/null
    dirs=$(find . -maxdepth 1 -mindepth 1 -type d)
    for dir in $dirs; do
        execute rm -rf $to/$dir
        execute cp -r $dir $to/$dir
    done
    popd > /dev/null
}

copy_file() {
    from=$1
    to=$2
    name=$(basename $from)

    execute rm $to/$name
    execute cp $from $to/$name
}

# Ensure the destination directories exist
# XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"

copy_dir .config $XDG_CONFIG_HOME
copy_dir .local $HOME/.local
copy_file .my_profile $HOME
copy_file .myrc $HOME