#!/usr/bin/env bash

git clone -b v0.11.2 https://github.com/neovim/neovim.git $HOME/workspaces/neovim

brew install cmake gettext lua@5.4

cd $HOME/workspaces/neovim
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install