#!/usr/bin/env bash

echo "Checking for ./.ready-tmux: $(ls -l ./.ready-tmux 2>/dev/null)" >&2
echo "Checking for ~/.ready-tmux: $(ls -l ~/.ready-tmux 2>/dev/null)" >&2

if [[ -x "./.ready-tmux" ]]; then
  echo "Running ./.ready-tmux" >&2
  ././.ready-tmux
elif [[ -x "$HOME/.ready-tmux" ]]; then
  echo "Running ~/.ready-tmux" >&2
  "$HOME/.ready-tmux"
else
  echo "No .ready-tmux script found in the current directory or home directory." >&2
  exit 2
fi