#!/usr/bin/env bash

if [[ -x ".ready-tmux" ]]; then
  echo "Running .ready-tmux script in the current directory..."
  ./.ready-tmux
elif [[ -x "~/.ready-tmux" ]]; then
  echo "Running .ready-tmux script in the home directory..."
  ~/.ready-tmux
else
  echo "No .ready-tmux script found in the current directory or home directory."
  exit 1
fi
clear